### ISSUE TITLE
Move ReadMe Docs to KDocs

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow#1490]
*This Issue addresses the incremental move towards KDocs as a Single Source of Truth regarding data types in Λrrow.*

#### Which Doc's need to be moved to Kdocs?
Under `modules/docs/arrow-docs/docs/_data/sidebar.yml` you can view a list of data types and their permalink:
```
  - title: Data Types

    nested_options:
    # ....
      - title: Option
        url: /docs/arrow/core/option/

      - title: Either
        url: /docs/arrow/core/either/

      - title: Try
        url: /docs/arrow/core/try/
```
Data types, which do not have a permalink starting with: `url: /docs/apidocs/...` are in the scope of this task, e.g.: Option, Either, Try, etc.

#### What needs to be done?
Essentially, we're trying to the same thing as in the last PR #1474  for the Id data type.
```
- LookUp the docs in `modules/docs/arrow-docs/docs/docs/arrow/data`
- [ ] Replace `kotlin:ank` -> `kotlin:ank:playground`
- [ ] Add specific imports avoid wildcard imports, but take this with a grain of salt
- [ ] Place the snippet over the data type declaration
- Test if everything runs: ./gradlew clean :arrow-docs:runAnk 
- Build the site locally (very long task): 
   ./gradlew clean dokka :arrow-docs:runAnk ;
   cd modules/docs/build/site; 
   jekyll serve;
- [ ] Replace the relativ permalink in sidebar.yaml with :  /docs/apidocs/<Path to data type>
```
A local build is required, because the remote build does not have your binaries. Hence, a remote lookup at the webpage won't be sufficient.
