### ISSUE TITLE
["Docs"] fixing input type="search" behaviour in Safari

### ISSUE THREAD

**Issue by rafalschmidt97** [arrow-kt/arrow#1757]
Hi,
I found that styles on safari (left) and chrome (right) for search bar are different. 

![Screenshot 2019-10-29 at 14 38 00](https://user-images.githubusercontent.com/14861637/67768059-65986e80-fa5a-11e9-964a-bded9336f767.png)

How to fix:

```css
input[type="search"] {
    -webkit-appearance: textfield;
}

input[type="search"]::-webkit-search-decoration {
    -webkit-appearance: none;
}
```

Details:
https://stackoverflow.com/a/34802612/7884071
https://mycyberuniverse.com/safari-chrome-default-styles-html5-search-input.html

I wanted to create a PR but I'm not sure if you want to prevent this globally or only for this search bar.

Anyway - great work for FP community. I'm super new in this field but resources in docs are really helpful.
